# Generated by Django 4.2.2 on 2023-07-02 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perevalapp', '0002_alter_perevaladded_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perevaladded',
            options={'verbose_name': 'Перевал', 'verbose_name_plural': 'Перевалы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='perevaladded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='perevalapp.users'),
        ),
    ]
